### PR TITLE
Add apple webpage 

### PR DESCRIPTION
**Pull request by rahalrazika**
## What does it do?
It clones the old web page 

## Tasks
- [x] The project setup  
- [x] Add the index HTML file 
- [x] Add the styling file 
- [x] Create professional ReadMe file
- [x] Implement the requested changes after review

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED :warning:
Hey @rahalrazika & @descholar-ceo :wave:
Good job so far! :tada: We have some few changes to do before we proceed (see review comment).
We, however, do have some few changes to carry out before we proceed (see review comment).
##
The [clone](https://raw.githack.com/rahalrazika/apple-old-webpage/add-apple-webpage/index.html) shows good understanding and usage of building with background gradients 💯 
We need no make sure nothing is messed up. Kindly see the differences below 👇 and work on the suggested changes.

|[Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/)|[Clone page](https://raw.githack.com/rahalrazika/apple-old-webpage/add-apple-webpage/index.html)|
|:---:|:---:|
|source|clone|
## Implementation details
### Background
- The CSS background should `cover` the whole page irrespective of the screen size. Kindly make good use of background-size and position properties. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/)).

- The four elements currently have spaces between them and above them with the main background cover. Kindly work on this. 

## OPTIONAL 
- Validate your CSS stylesheet with this [tool](https://jigsaw.w3.org/css-validator/validator).

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##

- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by descholar-ceo** [comment]
@christianotieno 

- [x] We changed the background-position and background-attachment and we let the background-size to `cover` so that it will cover any screen size, we think further page-adjustments depending on the screen sizes would require to play with some responsiveness which is covered in the coming lessons.

- [x] For the second requested change, (I mean the four elements on the bottom) we fixed the gap which was appearing on big screens, now kindly check it out.

- [x] On the optional request (Using [This tool](https://jigsaw.w3.org/css-validator/) ) for validation of CSS, we got confused about its validations, we originally used the linting tools as provided by Microverse [Linters from Microverse](https://github.com/descholar-ceo/linters-config/tree/master/html-css), and with that, we weren't getting any error, but with that tool, we got some, so what peace advice would you give us? To stick with that one or sticking on the Microverse's linting tool?

**Comment by andresporras3423** [comment]
### **Pull Request Under Review By Oscar Russi (TSE)**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**@rahalrazika @descholar-ceo** 
Good job so far :muscle:  
Your code pass the validations, your CSS has no problems :clap: :clap: :clap:  
Unfortunately, the link to your live demo is not working. It looks like this:



- [x] Try to use the next link to generate your live demo: https://raw.githack.com/

### OPTIONAL

- [x] it's recommended to use the main tag for the dominant content of your page.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Review by elmejdki — APPROVED** [review]
# Good job guys for implementing the TSE requirements :tophat: :blush: :clap: 
### status: approved

your project is approved you can now merge to master

### Happy Coding

**Pull request merged**
